### ISSUE TITLE
device_console package is missing

### ISSUE THREAD

**Issue by larsll** [aws-deepracer/aws-deepracer-launcher#6]
The instructions on https://github.com/aws-deepracer/aws-deepracer-launcher/blob/main/getting-started.md work well; with the exception that the files in `/opt/aws/deepracer/lib/device_console` are not public / part of the installation for a custom stack, and need to be kept/copied manually.

Files should probably be part of https://github.com/aws-deepracer/aws-deepracer-webserver-pkg

To specify a bit further:
"Running the latest packages" does not contain instructions on how to add device_console; the "Updating the deepracer-core service" should work, but as it copies 'on top' unclear what other remnants of the original build will stay.

**Comment by pratik-nichat** [comment]
Hello larsll@,
Thank you for your interest in the DeepRacer open source repositories. Currently, the device console is not part of the scope of the DeepRacer device opensourcing initiative.
